apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ubi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ubi
    app.kubernetes.io/part-of: rhel
  name: ubib4he
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ubi
    weight: 100
status: {}
