apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ubi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ubi
    app.kubernetes.io/part-of: rhel
  name: ubi
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: ubi
status:
  loadBalancer: {}
